GET http://localhost:5000/todos

####

POST http://localhost:5000/todos/new
Content-Type: application/json

{
    "title": "Get Timmy",
    "text": "Get my second bestfriend here"
}

### 

DELETE http://localhost:5000/todos/delete/63bc16bd5761fa536970d444

###

PUT http://localhost:5000/todos/update/63bc186ce3712851564957e2

